// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _digitrec_HH_
#define _digitrec_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "digitrec_trainingbkb.h"
#include "digitrec_knn_set_V.h"

namespace ap_rtl {

struct digitrec : public sc_module {
    // Port declarations 8
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<49> > input_V;
    sc_out< sc_lv<4> > ap_return;


    // Module declarations
    digitrec(sc_module_name name);
    SC_HAS_PROCESS(digitrec);

    ~digitrec();

    sc_trace_file* mVcdFile;

    digitrec_trainingbkb* training_data_V_U;
    digitrec_knn_set_V* knn_set_V_U;
    sc_signal< sc_lv<12> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<15> > training_data_V_address0;
    sc_signal< sc_logic > training_data_V_ce0;
    sc_signal< sc_lv<48> > training_data_V_q0;
    sc_signal< sc_lv<4> > i_fu_305_p2;
    sc_signal< sc_lv<4> > i_reg_598;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<6> > sub_ln321_fu_323_p2;
    sc_signal< sc_lv<6> > sub_ln321_reg_603;
    sc_signal< sc_lv<1> > icmp_ln58_fu_299_p2;
    sc_signal< sc_lv<2> > k_fu_335_p2;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<11> > i_1_fu_361_p2;
    sc_signal< sc_lv<11> > i_1_reg_619;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<15> > zext_ln64_fu_367_p1;
    sc_signal< sc_lv<15> > zext_ln64_reg_624;
    sc_signal< sc_lv<1> > icmp_ln63_fu_355_p2;
    sc_signal< sc_lv<15> > add_ln64_fu_371_p2;
    sc_signal< sc_lv<15> > add_ln64_reg_629;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<4> > j_fu_383_p2;
    sc_signal< sc_lv<4> > j_reg_637;
    sc_signal< sc_lv<1> > icmp_ln64_fu_377_p2;
    sc_signal< sc_lv<6> > sub_ln887_fu_411_p2;
    sc_signal< sc_lv<6> > sub_ln887_reg_647;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<49> > ret_V_fu_421_p2;
    sc_signal< sc_lv<49> > ret_V_reg_652;
    sc_signal< sc_lv<6> > i_3_fu_436_p2;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<6> > dist_V_fu_453_p2;
    sc_signal< sc_lv<1> > icmp_ln96_fu_430_p2;
    sc_signal< sc_lv<2> > i_4_fu_465_p2;
    sc_signal< sc_lv<2> > i_4_reg_673;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<5> > knn_set_V_addr_2_reg_678;
    sc_signal< sc_lv<1> > icmp_ln106_fu_459_p2;
    sc_signal< sc_lv<32> > zext_ln156_fu_491_p1;
    sc_signal< sc_lv<32> > zext_ln156_reg_686;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_lv<4> > i_2_fu_501_p2;
    sc_signal< sc_lv<4> > i_2_reg_694;
    sc_signal< sc_lv<6> > sub_ln544_fu_519_p2;
    sc_signal< sc_lv<6> > sub_ln544_reg_699;
    sc_signal< sc_lv<1> > icmp_ln139_fu_495_p2;
    sc_signal< sc_lv<2> > j_1_fu_535_p2;
    sc_signal< sc_lv<2> > j_1_reg_707;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_lv<1> > icmp_ln148_fu_529_p2;
    sc_signal< sc_lv<32> > select_ln154_fu_565_p3;
    sc_signal< sc_lv<32> > select_ln154_1_fu_572_p3;
    sc_signal< sc_lv<8> > distance_sum_fu_584_p2;
    sc_signal< sc_logic > ap_CS_fsm_state12;
    sc_signal< sc_lv<5> > knn_set_V_address0;
    sc_signal< sc_logic > knn_set_V_ce0;
    sc_signal< sc_logic > knn_set_V_we0;
    sc_signal< sc_lv<6> > knn_set_V_d0;
    sc_signal< sc_lv<6> > knn_set_V_q0;
    sc_signal< sc_lv<4> > i_0_reg_126;
    sc_signal< sc_lv<1> > icmp_ln59_fu_329_p2;
    sc_signal< sc_lv<2> > k_0_reg_137;
    sc_signal< sc_lv<11> > i4_0_reg_148;
    sc_signal< sc_lv<4> > j_0_reg_159;
    sc_signal< sc_lv<15> > phi_mul_reg_171;
    sc_signal< sc_lv<6> > curr_distance_V_reg_182;
    sc_signal< sc_lv<6> > bvh_d_index_reg_194;
    sc_signal< sc_lv<6> > p_016_0_i_reg_205;
    sc_signal< sc_lv<6> > ap_phi_mux_p_016_0_i_be_phi_fu_232_p4;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_lv<2> > i1_0_i_reg_217;
    sc_signal< sc_lv<1> > icmp_ln887_fu_485_p2;
    sc_signal< sc_lv<32> > val_assign_reg_241;
    sc_signal< sc_lv<32> > min_sum_0_i_reg_253;
    sc_signal< sc_lv<4> > result_reg_265;
    sc_signal< sc_lv<8> > min_sum_reg_276;
    sc_signal< sc_lv<2> > j_0_i_reg_288;
    sc_signal< sc_lv<64> > sext_ln321_fu_350_p1;
    sc_signal< sc_lv<64> > zext_ln66_1_fu_394_p1;
    sc_signal< sc_lv<64> > sext_ln887_fu_480_p1;
    sc_signal< sc_lv<64> > sext_ln544_fu_550_p1;
    sc_signal< sc_lv<6> > tmp_1_fu_315_p3;
    sc_signal< sc_lv<6> > zext_ln321_fu_311_p1;
    sc_signal< sc_lv<6> > zext_ln321_1_fu_341_p1;
    sc_signal< sc_lv<6> > add_ln321_fu_345_p2;
    sc_signal< sc_lv<15> > add_ln66_fu_389_p2;
    sc_signal< sc_lv<6> > tmp_3_fu_403_p3;
    sc_signal< sc_lv<6> > zext_ln66_fu_399_p1;
    sc_signal< sc_lv<49> > zext_ln66_2_fu_417_p1;
    sc_signal< sc_lv<32> > zext_ln101_fu_426_p1;
    sc_signal< sc_lv<1> > p_Result_s_fu_442_p3;
    sc_signal< sc_lv<6> > zext_ln700_fu_449_p1;
    sc_signal< sc_lv<6> > zext_ln887_fu_471_p1;
    sc_signal< sc_lv<6> > add_ln887_fu_475_p2;
    sc_signal< sc_lv<6> > tmp_2_fu_511_p3;
    sc_signal< sc_lv<6> > zext_ln544_fu_507_p1;
    sc_signal< sc_lv<6> > zext_ln544_1_fu_541_p1;
    sc_signal< sc_lv<6> > add_ln544_fu_545_p2;
    sc_signal< sc_lv<32> > zext_ln155_fu_555_p1;
    sc_signal< sc_lv<1> > icmp_ln154_fu_559_p2;
    sc_signal< sc_lv<8> > zext_ln149_fu_580_p1;
    sc_signal< sc_lv<4> > trunc_ln301_fu_525_p1;
    sc_signal< sc_lv<4> > ap_return_preg;
    sc_signal< sc_lv<12> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<12> ap_ST_fsm_state1;
    static const sc_lv<12> ap_ST_fsm_state2;
    static const sc_lv<12> ap_ST_fsm_state3;
    static const sc_lv<12> ap_ST_fsm_state4;
    static const sc_lv<12> ap_ST_fsm_state5;
    static const sc_lv<12> ap_ST_fsm_state6;
    static const sc_lv<12> ap_ST_fsm_state7;
    static const sc_lv<12> ap_ST_fsm_state8;
    static const sc_lv<12> ap_ST_fsm_state9;
    static const sc_lv<12> ap_ST_fsm_state10;
    static const sc_lv<12> ap_ST_fsm_state11;
    static const sc_lv<12> ap_ST_fsm_state12;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<11> ap_const_lv11_0;
    static const sc_lv<15> ap_const_lv15_0;
    static const sc_lv<6> ap_const_lv6_0;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_96;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_lv<6> ap_const_lv6_32;
    static const sc_lv<4> ap_const_lv4_A;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<11> ap_const_lv11_708;
    static const sc_lv<11> ap_const_lv11_1;
    static const sc_lv<15> ap_const_lv15_708;
    static const sc_lv<6> ap_const_lv6_31;
    static const sc_lv<6> ap_const_lv6_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_add_ln321_fu_345_p2();
    void thread_add_ln544_fu_545_p2();
    void thread_add_ln64_fu_371_p2();
    void thread_add_ln66_fu_389_p2();
    void thread_add_ln887_fu_475_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_phi_mux_p_016_0_i_be_phi_fu_232_p4();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_dist_V_fu_453_p2();
    void thread_distance_sum_fu_584_p2();
    void thread_i_1_fu_361_p2();
    void thread_i_2_fu_501_p2();
    void thread_i_3_fu_436_p2();
    void thread_i_4_fu_465_p2();
    void thread_i_fu_305_p2();
    void thread_icmp_ln106_fu_459_p2();
    void thread_icmp_ln139_fu_495_p2();
    void thread_icmp_ln148_fu_529_p2();
    void thread_icmp_ln154_fu_559_p2();
    void thread_icmp_ln58_fu_299_p2();
    void thread_icmp_ln59_fu_329_p2();
    void thread_icmp_ln63_fu_355_p2();
    void thread_icmp_ln64_fu_377_p2();
    void thread_icmp_ln887_fu_485_p2();
    void thread_icmp_ln96_fu_430_p2();
    void thread_j_1_fu_535_p2();
    void thread_j_fu_383_p2();
    void thread_k_fu_335_p2();
    void thread_knn_set_V_address0();
    void thread_knn_set_V_ce0();
    void thread_knn_set_V_d0();
    void thread_knn_set_V_we0();
    void thread_p_Result_s_fu_442_p3();
    void thread_ret_V_fu_421_p2();
    void thread_select_ln154_1_fu_572_p3();
    void thread_select_ln154_fu_565_p3();
    void thread_sext_ln321_fu_350_p1();
    void thread_sext_ln544_fu_550_p1();
    void thread_sext_ln887_fu_480_p1();
    void thread_sub_ln321_fu_323_p2();
    void thread_sub_ln544_fu_519_p2();
    void thread_sub_ln887_fu_411_p2();
    void thread_tmp_1_fu_315_p3();
    void thread_tmp_2_fu_511_p3();
    void thread_tmp_3_fu_403_p3();
    void thread_training_data_V_address0();
    void thread_training_data_V_ce0();
    void thread_trunc_ln301_fu_525_p1();
    void thread_zext_ln101_fu_426_p1();
    void thread_zext_ln149_fu_580_p1();
    void thread_zext_ln155_fu_555_p1();
    void thread_zext_ln156_fu_491_p1();
    void thread_zext_ln321_1_fu_341_p1();
    void thread_zext_ln321_fu_311_p1();
    void thread_zext_ln544_1_fu_541_p1();
    void thread_zext_ln544_fu_507_p1();
    void thread_zext_ln64_fu_367_p1();
    void thread_zext_ln66_1_fu_394_p1();
    void thread_zext_ln66_2_fu_417_p1();
    void thread_zext_ln66_fu_399_p1();
    void thread_zext_ln700_fu_449_p1();
    void thread_zext_ln887_fu_471_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
